// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DrivingData.proto

package com.tadah.vehicle.dtos;

public final class DrivingDataProto {
  private DrivingDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code DrivingStatus}
   */
  public enum DrivingStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>START = 0;</code>
     */
    START(0),
    /**
     * <code>DRIVING = 1;</code>
     */
    DRIVING(1),
    /**
     * <code>STOP = 2;</code>
     */
    STOP(2),
    ;

    /**
     * <code>START = 0;</code>
     */
    public static final int START_VALUE = 0;
    /**
     * <code>DRIVING = 1;</code>
     */
    public static final int DRIVING_VALUE = 1;
    /**
     * <code>STOP = 2;</code>
     */
    public static final int STOP_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DrivingStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DrivingStatus forNumber(int value) {
      switch (value) {
        case 0: return START;
        case 1: return DRIVING;
        case 2: return STOP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DrivingStatus>
    internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DrivingStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DrivingStatus>() {
          public DrivingStatus findValueByNumber(int number) {
            return DrivingStatus.forNumber(number);
          }
        };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return DrivingDataProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final DrivingStatus[] VALUES = values();

    public static DrivingStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DrivingStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DrivingStatus)
  }

  public interface DrivingDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DrivingData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 userId = 1;</code>
     * @return Whether the userId field is set.
     */
    boolean hasUserId();
    /**
     * <code>required int64 userId = 1;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>required double latitude = 2;</code>
     * @return Whether the latitude field is set.
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 2;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>required double longitude = 3;</code>
     * @return Whether the longitude field is set.
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 3;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <code>required .DrivingStatus drivingStatus = 4 [default = START];</code>
     * @return Whether the drivingStatus field is set.
     */
    boolean hasDrivingStatus();
    /**
     * <code>required .DrivingStatus drivingStatus = 4 [default = START];</code>
     * @return The drivingStatus.
     */
    DrivingDataProto.DrivingStatus getDrivingStatus();
  }
  /**
   * Protobuf type {@code DrivingData}
   */
  public static final class DrivingData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DrivingData)
      DrivingDataOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use DrivingData.newBuilder() to construct.
    private DrivingData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DrivingData() {
      drivingStatus_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DrivingData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DrivingData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              latitude_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              longitude_ = input.readDouble();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
              DrivingDataProto.DrivingStatus value = DrivingDataProto.DrivingStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                drivingStatus_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return DrivingDataProto.internal_static_DrivingData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return DrivingDataProto.internal_static_DrivingData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DrivingDataProto.DrivingData.class, DrivingDataProto.DrivingData.Builder.class);
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>required int64 userId = 1;</code>
     * @return Whether the userId field is set.
     */
    @java.lang.Override
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 2;
    private double latitude_;
    /**
     * <code>required double latitude = 2;</code>
     * @return Whether the latitude field is set.
     */
    @java.lang.Override
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required double latitude = 2;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 3;
    private double longitude_;
    /**
     * <code>required double longitude = 3;</code>
     * @return Whether the longitude field is set.
     */
    @java.lang.Override
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required double longitude = 3;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }

    public static final int DRIVINGSTATUS_FIELD_NUMBER = 4;
    private int drivingStatus_;
    /**
     * <code>required .DrivingStatus drivingStatus = 4 [default = START];</code>
     * @return Whether the drivingStatus field is set.
     */
    @java.lang.Override public boolean hasDrivingStatus() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required .DrivingStatus drivingStatus = 4 [default = START];</code>
     * @return The drivingStatus.
     */
    @java.lang.Override public DrivingDataProto.DrivingStatus getDrivingStatus() {
      @SuppressWarnings("deprecation")
      DrivingDataProto.DrivingStatus result = DrivingDataProto.DrivingStatus.valueOf(drivingStatus_);
      return result == null ? DrivingDataProto.DrivingStatus.START : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDrivingStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, longitude_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(4, drivingStatus_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, longitude_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(4, drivingStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof DrivingDataProto.DrivingData)) {
        return super.equals(obj);
      }
      DrivingDataProto.DrivingData other = (DrivingDataProto.DrivingData) obj;

      if (hasUserId() != other.hasUserId()) return false;
      if (hasUserId()) {
        if (getUserId()
            != other.getUserId()) return false;
      }
      if (hasLatitude() != other.hasLatitude()) return false;
      if (hasLatitude()) {
        if (java.lang.Double.doubleToLongBits(getLatitude())
            != java.lang.Double.doubleToLongBits(
            other.getLatitude())) return false;
      }
      if (hasLongitude() != other.hasLongitude()) return false;
      if (hasLongitude()) {
        if (java.lang.Double.doubleToLongBits(getLongitude())
            != java.lang.Double.doubleToLongBits(
            other.getLongitude())) return false;
      }
      if (hasDrivingStatus() != other.hasDrivingStatus()) return false;
      if (hasDrivingStatus()) {
        if (drivingStatus_ != other.drivingStatus_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserId()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUserId());
      }
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatitude()));
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
      }
      if (hasDrivingStatus()) {
        hash = (37 * hash) + DRIVINGSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + drivingStatus_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DrivingDataProto.DrivingData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DrivingDataProto.DrivingData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DrivingDataProto.DrivingData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DrivingDataProto.DrivingData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DrivingDataProto.DrivingData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DrivingDataProto.DrivingData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DrivingDataProto.DrivingData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DrivingDataProto.DrivingData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DrivingDataProto.DrivingData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DrivingDataProto.DrivingData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DrivingDataProto.DrivingData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DrivingDataProto.DrivingData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DrivingDataProto.DrivingData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DrivingData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DrivingData)
        DrivingDataProto.DrivingDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return DrivingDataProto.internal_static_DrivingData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return DrivingDataProto.internal_static_DrivingData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DrivingDataProto.DrivingData.class, DrivingDataProto.DrivingData.Builder.class);
      }

      // Construct using com.tadah.vehicle.dtos.DrivingDataProto.DrivingData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
            .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        drivingStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return DrivingDataProto.internal_static_DrivingData_descriptor;
      }

      @java.lang.Override
      public DrivingDataProto.DrivingData getDefaultInstanceForType() {
        return DrivingDataProto.DrivingData.getDefaultInstance();
      }

      @java.lang.Override
      public DrivingDataProto.DrivingData build() {
        DrivingDataProto.DrivingData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DrivingDataProto.DrivingData buildPartial() {
        DrivingDataProto.DrivingData result = new DrivingDataProto.DrivingData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.latitude_ = latitude_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.longitude_ = longitude_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.drivingStatus_ = drivingStatus_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DrivingDataProto.DrivingData) {
          return mergeFrom((DrivingDataProto.DrivingData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DrivingDataProto.DrivingData other) {
        if (other == DrivingDataProto.DrivingData.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasDrivingStatus()) {
          setDrivingStatus(other.getDrivingStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasUserId()) {
          return false;
        }
        if (!hasLatitude()) {
          return false;
        }
        if (!hasLongitude()) {
          return false;
        }
        if (!hasDrivingStatus()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DrivingDataProto.DrivingData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DrivingDataProto.DrivingData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <code>required int64 userId = 1;</code>
       * @return Whether the userId field is set.
       */
      @java.lang.Override
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 userId = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>required double latitude = 2;</code>
       * @return Whether the latitude field is set.
       */
      @java.lang.Override
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double latitude = 2;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 2;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000002;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>required double longitude = 3;</code>
       * @return Whether the longitude field is set.
       */
      @java.lang.Override
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required double longitude = 3;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 3;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000004;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private int drivingStatus_ = 0;
      /**
       * <code>required .DrivingStatus drivingStatus = 4 [default = START];</code>
       * @return Whether the drivingStatus field is set.
       */
      @java.lang.Override public boolean hasDrivingStatus() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required .DrivingStatus drivingStatus = 4 [default = START];</code>
       * @return The drivingStatus.
       */
      @java.lang.Override
      public DrivingDataProto.DrivingStatus getDrivingStatus() {
        @SuppressWarnings("deprecation")
        DrivingDataProto.DrivingStatus result = DrivingDataProto.DrivingStatus.valueOf(drivingStatus_);
        return result == null ? DrivingDataProto.DrivingStatus.START : result;
      }
      /**
       * <code>required .DrivingStatus drivingStatus = 4 [default = START];</code>
       * @param value The drivingStatus to set.
       * @return This builder for chaining.
       */
      public Builder setDrivingStatus(DrivingDataProto.DrivingStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        drivingStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .DrivingStatus drivingStatus = 4 [default = START];</code>
       * @return This builder for chaining.
       */
      public Builder clearDrivingStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        drivingStatus_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DrivingData)
    }

    // @@protoc_insertion_point(class_scope:DrivingData)
    private static final DrivingDataProto.DrivingData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DrivingDataProto.DrivingData();
    }

    public static DrivingDataProto.DrivingData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DrivingData>
        PARSER = new com.google.protobuf.AbstractParser<DrivingData>() {
      @java.lang.Override
      public DrivingData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DrivingData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DrivingData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DrivingData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DrivingDataProto.DrivingData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_DrivingData_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DrivingData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
        "\n\021DrivingData.proto\"p\n\013DrivingData\022\016\n\006us" +
            "erId\030\001 \002(\003\022\020\n\010latitude\030\002 \002(\001\022\021\n\tlongitud" +
            "e\030\003 \002(\001\022,\n\rdrivingStatus\030\004 \002(\0162\016.Driving" +
            "Status:\005START*1\n\rDrivingStatus\022\t\n\005START\020" +
            "\000\022\013\n\007DRIVING\020\001\022\010\n\004STOP\020\002B*\n\026com.tadah.dr" +
            "iving.dtosB\020DrivingDataProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
            });
    internal_static_DrivingData_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_DrivingData_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DrivingData_descriptor,
        new java.lang.String[] { "UserId", "Latitude", "Longitude", "DrivingStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
