name: Ta-Dah Server CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - server/**
    paths-ignore:
      - "server/test/**"
      - "**/*.md"
jobs:
  build:
    name: Ta-Dah Server Build
    runs-on: ubuntu-latest
    environment: SERVER_TEST
    env:
      working-directory: server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.0

      - name: SetUp Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 15.0.2
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      - name: Spring Test
        run: STREAM_NAME=${{ secrets.STREAM_NAME }} AWS_PRODUCER_ACCESS_KEY=${{ secrets.AWS_PRODUCER_ACCESS_KEY }} AWS_PRODUCER_SECRET_KEY=${{ secrets.AWS_PRODUCER_SECRET_KEY }} AWS_REGION=${{ secrets.AWS_REGION }} JWT_SECRET=${{ secrets.JWT_SECRET }} ./gradlew test jacocoTestCoverageVerification
        working-directory: ${{ env.working-directory }}